// <auto-generated />
using System;
using Kviz.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kviz.Core.Migrations
{
    [DbContext(typeof(KvizDbContext))]
    [Migration("20260225163144_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.24");

            modelBuilder.Entity("Kviz.Core.Ispit", b =>
                {
                    b.Property<int>("Sifra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfesorUsername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Sifra");

                    b.HasIndex("ProfesorUsername");

                    b.ToTable("Ispiti");
                });

            modelBuilder.Entity("Kviz.Core.Korisnik", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipKorisnika")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.HasKey("Username");

                    b.ToTable("Korisnici");

                    b.HasDiscriminator<string>("TipKorisnika").HasValue("Korisnik");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Kviz.Core.Pitanje", b =>
                {
                    b.Property<int>("PitanjeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IspitId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PitanjeTekst")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipPitanja")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.HasKey("PitanjeId");

                    b.HasIndex("IspitId");

                    b.ToTable("Pitanja");

                    b.HasDiscriminator<string>("TipPitanja").HasValue("Pitanje");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Kviz.Core.Rezultat", b =>
                {
                    b.Property<int>("RezultatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrojTocnihOdgovora")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<int>("IspitId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StudentUsername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RezultatId");

                    b.HasIndex("IspitId");

                    b.HasIndex("StudentUsername");

                    b.ToTable("Rezultati");
                });

            modelBuilder.Entity("Kviz.Core.Profesor", b =>
                {
                    b.HasBaseType("Kviz.Core.Korisnik");

                    b.HasDiscriminator().HasValue("Profesor");

                    b.HasData(
                        new
                        {
                            Username = "profesor",
                            Password = "87654321"
                        });
                });

            modelBuilder.Entity("Kviz.Core.Student", b =>
                {
                    b.HasBaseType("Kviz.Core.Korisnik");

                    b.HasDiscriminator().HasValue("Student");

                    b.HasData(
                        new
                        {
                            Username = "student",
                            Password = "12345678"
                        });
                });

            modelBuilder.Entity("Kviz.Core.InputPitanje", b =>
                {
                    b.HasBaseType("Kviz.Core.Pitanje");

                    b.Property<string>("OdgovorTocanJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OdgovorUnesen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Input");
                });

            modelBuilder.Entity("Kviz.Core.SingleChoicePitanje", b =>
                {
                    b.HasBaseType("Kviz.Core.Pitanje");

                    b.Property<char>("OdgovorTocan")
                        .HasColumnType("TEXT");

                    b.Property<char>("OdgovorUneseni")
                        .HasColumnType("TEXT");

                    b.Property<string>("PonudeniOdgJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("SingleChoice");
                });

            modelBuilder.Entity("Kviz.Core.Ispit", b =>
                {
                    b.HasOne("Kviz.Core.Profesor", "Profesor")
                        .WithMany("Ispiti")
                        .HasForeignKey("ProfesorUsername")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("Kviz.Core.Pitanje", b =>
                {
                    b.HasOne("Kviz.Core.Ispit", "Ispit")
                        .WithMany("SkupPitanja")
                        .HasForeignKey("IspitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ispit");
                });

            modelBuilder.Entity("Kviz.Core.Rezultat", b =>
                {
                    b.HasOne("Kviz.Core.Ispit", "Ispit")
                        .WithMany()
                        .HasForeignKey("IspitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kviz.Core.Student", "Student")
                        .WithMany("Rezultati")
                        .HasForeignKey("StudentUsername")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ispit");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Kviz.Core.Ispit", b =>
                {
                    b.Navigation("SkupPitanja");
                });

            modelBuilder.Entity("Kviz.Core.Profesor", b =>
                {
                    b.Navigation("Ispiti");
                });

            modelBuilder.Entity("Kviz.Core.Student", b =>
                {
                    b.Navigation("Rezultati");
                });
#pragma warning restore 612, 618
        }
    }
}
